sudo: required

# install Docker
services:
  - docker

# Execute logic
script:
  - echo "Hello"

after_success:
# build all the docker files
  - docker build -t prabhashbhajani/zomato-clone-client ./client
  - docker build -t prabhashbhajani/zomato-clone-server ./server
  - docker build -t prabhashbhajani/zomato-clone-nginx ./nginx

  # log in to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # push to docker hub
  - docker push prabhashbhajani/zomato-clone-client
  - docker push prabhashbhajani/zomato-clone-server
  - docker push prabhashbhajani/zomato-clone-nginx

deploy:
  # deploy to AWS EBS
  provider: elasticbeanstalk
  region: ap-south-1
  app: Zomato-Clone
  env: Zomatoclone-env
  bucket: elasticbeanstalk-ap-south-1-418278132541
  bucket_path: zomatoclone
  on:
    branch: master
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET